force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Response__c/Module_Response__c.object-meta.xml
<CustomObject>
    <label>Module Response</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Module Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Module Response</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Response__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Module Response</relationshipLabel>
    <relationshipName>Module_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module_Response__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Module Response</relationshipLabel>
    <relationshipName>Module_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Response__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Module Response</relationshipLabel>
    <relationshipName>Module_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit Response</label>
    <nameField>
        <displayFormat>UR-{0000}</displayFormat>
        <label>Unit Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Response__c/fields/Module_Response__c.field-meta.xml
<CustomField>
    <fullName>Module_Response__c</fullName>
    <label>Module Response</label>
    <referenceTo>Module_Response__c</referenceTo>
    <relationshipLabel>Unit Response</relationshipLabel>
    <relationshipName>Unit_Response</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Number_of_tries__c.field-meta.xml
<CustomField>
    <fullName>Number_of_tries__c</fullName>
    <label>Number of tries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Response</relationshipLabel>
    <relationshipName>Unit_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UnitService.cls
public class UnitService {
    public static Boolean registerUnitResponse(Id unitId, String jsonAnswer){
        
        // Setting a save point to make a rollback
        Database.SavePoint sp = Database.setSavePoint();

        try{
            // I query the student Id
            Student__c student = [SELECT Id FROM Student__c WHERE  User__c =: Userinfo.getUserId()];
            
            // I query the unit from the database and subquery the related questions
            Unit__c unit = [SELECT Module__c,(SELECT Id, Number_of_tries__c FROM UnitResponses__c WHERE ModuleResponse__r.Student__c =: student.Id ORDER BY Number_of_tries__c DESC LIMIT 1), (SELECT Id, Name FROM Questions__r) FROM Unit__c WHERE Id =: unitId];
            
            // I verify if the module response already exists
            Module_Response__c moduleResp = [SELECT Id FROM Module_Response__c WHERE Module__c =: unit.Module__c AND Student__c =: student.Id AND Status__c = 'In Progress'];

            // If it doesn't exist:
            if(moduleResp == null){
                // I create and insert the Module Response
                Module_Response__c moduleResp = new Module_Response__c(Student__c = student.Id, Module__c = unit.Module__c, Status__c = 'In Progress');
                insert moduleResp;
            }

            // I create and insert the Unit Response 
            Unit_Response__c unitResp = new Unit_Response__c(Unit__c = unitId, Student__c = student.Id, Module_Response__c = moduleResp.Id, Status__c = 'Draft');
            insert unitResp;
            
            // NTH
            unitResp.Number_of_tries__c = !unit.Unit_Responses__c.isEmpty() ? unit.Unit_Response__c[0].Number_of_tries__c + 1 : 1;
            insert unitResp;
            
            // I create and load the questions responses
            Map<Id,Id> answerMap = (Map<Id,Id>)JSON.deserializeStrict(jsonAnswer,Map<Id,Id>.class);
            List<QuestionResponse__c> questionRespList = new List<QuestionResponse__c>();
            //for(Id questionId : answerMap.keySet()){
            for(Question__c question : unit.Questions__r){
                // I check if the question was answered in the map
                if(answerMap.containsKey(questionId)){
                    QuestionResponse__c questionResp = new questionResponce__c(Question__c = question.Id, Unit_Response__c = unitResp.Id, Option__c = answerMap.get(question.Id));
                questionRespList.add(questionResp);
                }else{
                    throw new CustomException('The question ' + question.Name + ' was not answered and is required');
                }
            }
            insert questionRespList;

            // I update the unit response status to 'Answered' to trigger the evaluation process
            unitResp.Status__c = 'Answered';
            update unitResp;
        }catch(Exception e){
            Database.rollback(sp);
            throw e;
        }
    }
}